---
- hosts: localhost
  gather_facts: no
  vars_files:
        - awscred.yml
  tasks:
    - name: Running EC2 Role, Creating EC2 instances along with Security Group
      include_role:
        name: ec2

- hosts: ec2_master
  gather_facts: no
  tasks:
    - name: Running K8s Master Role
      include_role:
        name: k8s_master

- hosts: localhost
  gather_facts: no
  vars_files:
    - awscred.yml
  name: Creating Load Balancer and attaching master instance to it
  roles:
   - role: loadbalancer
     vars:
        security_group_id: "{{hostvars.localhost.securitygroup.group_id|string}}"
        master_node_id: "{{id[0]}}"


- hosts: ec2_slave
  gather_facts: no
  tasks:
    - name: Running K8s Slave Role
      include_role:
        name: k8s_slave

- hosts: ec2_master
  gather_facts: no
  tasks:
    - name: Deploying Pods
      include_role:
        name: pods

- hosts: localhost
  gather_facts: no
  vars_files:
    - awscred.yml
  name: Assigning Elastic IP address to each instance
  roles:
   - role: elastic_ip_address
     vars:
        id: "{{id}}"
