---
- amazon.aws.elb_classic_lb:
    name: "{{name}}"
    state: present
    region: "{{region_name}}"
    security_group_ids: "sg-025af8886cd0cb166"
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    zones:
      - "{{region_name}}b"
    listeners:
      - protocol: http # options are http, https, ssl, tcp
        load_balancer_port: 80
        instance_port: 80
        proxy_protocol: True

- name: add EC2 Instances to AWS ELB
  community.aws.elb_instance:
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        instance_id: "{{item}}"
        ec2_elbs: "{{name}}"
        state: present
        region: "{{region_name}}"
  loop:
    - i-002d4ef7fa11d03e3
    - i-0893b58b34fd137d5
    - i-007c6fe6aaf1a6fa4 
