---
# tasks file for elastic_ip_address
- name: associate new elastic IPs with each of the instances
  community.aws.ec2_eip:
    device_id: "{{ item }}"
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    region: "{{region_name}}"
  loop: "{{id}}"
  register: eip

