---
- name: create Docker config directory
  file: path=/etc/docker state=directory

- name: changing Docker to systemd driver
  copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }

- name: install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true
                   
- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present
      
- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
        
- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
     
- name: install kubelet
  apt:
    name: kubelet=1.22.4-00
    state: present
    update_cache: true

- name: install kubeadm
  apt:
    name: kubeadm=1.22.4-00
    state: present

- name: Updating IP tables on Slave Node
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Reloading sysctl on Slave Node
  command: sysctl --system

- name: Joining the master node
  command: "{{ hostvars[groups['ec2_master'][0]]['token']['stdout'] }}"

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches
