---
# tasks file for pods
- name: Creating Persistent Volumes
  command: kubectl apply -f https://raw.githubusercontent.com/mattavicoder/catalog_k8_files/master/pvc.yaml

- name: Deploying Mongodb Headless state
  command: kubectl apply -f https://raw.githubusercontent.com/mattavicoder/catalog_k8_files/master/mongodb.yaml

- name: Deploying Catalog API and catalog-service
  command: kubectl apply -f https://raw.githubusercontent.com/mattavicoder/catalog_k8_files/master/catalog.yaml

- name: Deploying Catalog UI and catalog-items-service
  command: kubectl apply -f https://raw.githubusercontent.com/mattavicoder/catalog_k8_files/master/catalogitems.yaml

- name: Deploying Horizontal AutoScale for Catalog Items UI
  command: kubectl apply -f https://raw.githubusercontent.com/mattavicoder/catalog_k8_files/master/catalogitems-horizontalautoscale.yaml

- name: Deploying Network policy between MongoDb and catalog Api
  command: kubectl apply -f https://raw.githubusercontent.com/mattavicoder/catalog_k8_files/master/catalog-mongodb-networkpolicy.yaml
  
- name: Deploying Ingress for Catalog API, Catalog UI services
  command: sudo kubectl apply -f https://raw.githubusercontent.com/mattavicoder/catalog_k8_files/master/k8.yml

